[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    knolleary/PubSubClient @ ^2.8.0
    bblanchon/ArduinoJson @ ^7.0.0
    tzapu/WiFiManager @ ^2.0.17

monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -DMQTT_MAX_PACKET_SIZE=512

board_build.partitions = min_spiffs.csv